### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by dhayford92** [armandsalle/my-site#4]
undefined is not iterable (cannot read property Symbol(Symbol.iterator)).

This happens when you try to select a country

**Comment by armandsalle** [comment]
Hey, I've fixed this issue 3 weeks ago. I don't reproduce it with my demo. Can you tell me more about your project setup?

**Comment by paveldotsmirnov** [comment]
This happens on your live preview too
![image](https://github.com/armandsalle/my-site/assets/93135086/5816e4e1-acb8-4b22-a82e-4e218b31c843)

**Comment by armandsalle** [comment]
My bad I was focusing on the other component 😅 I will fix this next week 👍

**Comment by armandsalle** [comment]
I think I've fixed it, I was missing the `<CommandList>` component from `cmdk`
check this commit https://github.com/armandsalle/my-site/commit/e00b412d47d95e0b613c793e1d804f14fd09d7b0

**Comment by armandsalle** [comment]
I've fixed the issue
