### ISSUE TITLE
Autocomplete select not working

### ISSUE THREAD

**Issue by ImamJanjua** [armandsalle/my-site#6]
https://github.com/armandsalle/my-site/assets/137432044/f62ebd9f-899a-4dd9-9e45-ac593c2b409d

hey man, as u can see in the clip I cannot select anything like with mouse but only with keyboard

**Comment by armandsalle** [comment]
Hey, what version of CMDK and radix are you using?

**Comment by NEOdinok** [comment]
@ImamJanjua 

I had the same issue. Check how you are importing those:
`import { CommandGroup, CommandInput, CommandItem, CommandList } from "./ui/command";`

Notice they are imported from ui lib here. You should go to /ui and copy those components the way they are in the repo.
(They are not shadcn default components)

**Comment by armandsalle** [comment]
Yes this is something to take care off. Writing an ESLint rule can be useful for that.
Thank you @NEOdinok for your clarification
