### ISSUE TITLE
example in Form Shadn UI

### ISSUE THREAD

**Issue by efgomes** [armandsalle/my-site#7]
Hi, could you provide an example of use within a Shadcn Ui form, I want to use it to perform patient feth in the backend, thank you very much

**Comment by efgomes** [comment]
what method can I capture the onChange of the input?

![image](https://github.com/user-attachments/assets/f7293b45-92dd-4a1d-b6ea-01880b45b24f)
When you change to call the function to fetch data from the api, you need to render this data in options

**Comment by armandsalle** [comment]
Hey @efgomes I don't use the Form solution provided by Shadcn, I go with `react-hook-form` from scratch most of the time.
If you want to plug a component in a form, look at what I did for the phone input, it should give you an idea on how to implement your own way https://github.com/armandsalle/my-site/issues/5

**Comment by armandsalle** [comment]
> what method can I capture the onChange of the input?
> 
> ![image](https://private-user-images.githubusercontent.com/53862865/351265618-f7293b45-92dd-4a1d-b6ea-01880b45b24f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Mjc3MTIsIm5iZiI6MTcyMTcyNzQxMiwicGF0aCI6Ii81Mzg2Mjg2NS8zNTEyNjU2MTgtZjcyOTNiNDUtOTJkZC00YTFkLWI2ZWEtMDE4ODBiNDViMjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA5MzY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1N2EyNjBkOGQ3ZTVmZmNhYjBkYTgyZTUwYmNkZjQzNjk0MGU2MzgzNGEyNzEyNjM5YTc1NmFiYTg3MTBiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6SrPF6Zr7Gp7LRA4O3ZuhponLAGwYOYvLlNcFxFyK6k) When you change to call the function to fetch data from the api, you need to render this data in options

I'm not sure to understand your questions, can you give an example or more details please?

**Comment by efgomes** [comment]
Hello friend, so I need to access the onChange property, every change that triggers an API call to the backend, I'm using the shadcnui form, it is built on the react form hook the onValueChange method returns the item when it is selected and this is correct, I miss the method to trigger when the input is changed
